### ISSUE TITLE
using .ini file as plotting param

### ISSUE THREAD

**Issue by SSingh087** [Relativist1/Tardis#1]
```
plt.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['mathtext.fontset'] = 'stix'
plt.rcParams['font.size'] = 18
```
so these are plotting param and I'm sure there are going to be more in the future since it is still in development. SO what I'm saying is that you can have a .ini file like
```
[param]
font.family = 'Times New Roman'
'mathtext.fontset' = 'stix'
'font.size' = 18
[other param]
```
and the config file can be read via a different script that passes this pram to the tardis.py

**Comment by Relativist1** [comment]
Yes, will be adding that sort of thing!
